window.esdocSearchIndex = [
  [
    "./components/addcategoryform.js~addcategoryform",
    "class/components/AddCategoryForm.js~AddCategoryForm.html",
    "<span>AddCategoryForm</span> <span class=\"search-result-import-path\">./components/AddCategoryForm.js</span>",
    "class"
  ],
  [
    "./components/additemform.js~additemform",
    "class/components/AddItemForm.js~AddItemForm.html",
    "<span>AddItemForm</span> <span class=\"search-result-import-path\">./components/AddItemForm.js</span>",
    "class"
  ],
  [
    "./components/category.js~category",
    "class/components/Category.js~Category.html",
    "<span>Category</span> <span class=\"search-result-import-path\">./components/Category.js</span>",
    "class"
  ],
  [
    "./components/component.js~component",
    "class/components/Component.js~Component.html",
    "<span>Component</span> <span class=\"search-result-import-path\">./components/Component.js</span>",
    "class"
  ],
  [
    "./components/deletecategoryform.js~deletecategoryform",
    "class/components/DeleteCategoryForm.js~DeleteCategoryForm.html",
    "<span>DeleteCategoryForm</span> <span class=\"search-result-import-path\">./components/DeleteCategoryForm.js</span>",
    "class"
  ],
  [
    "./components/deleteitemform.js~deleteitemform",
    "class/components/DeleteItemForm.js~DeleteItemForm.html",
    "<span>DeleteItemForm</span> <span class=\"search-result-import-path\">./components/DeleteItemForm.js</span>",
    "class"
  ],
  [
    "./components/editcategoryform.js~editcategoryform",
    "class/components/EditCategoryForm.js~EditCategoryForm.html",
    "<span>EditCategoryForm</span> <span class=\"search-result-import-path\">./components/EditCategoryForm.js</span>",
    "class"
  ],
  [
    "./components/edititemform.js~edititemform",
    "class/components/EditItemForm.js~EditItemForm.html",
    "<span>EditItemForm</span> <span class=\"search-result-import-path\">./components/EditItemForm.js</span>",
    "class"
  ],
  [
    "./components/googleauth2.js~googleauth2",
    "class/components/GoogleAuth2.js~GoogleAuth2.html",
    "<span>GoogleAuth2</span> <span class=\"search-result-import-path\">./components/GoogleAuth2.js</span>",
    "class"
  ],
  [
    "./components/item.js~item",
    "class/components/Item.js~Item.html",
    "<span>Item</span> <span class=\"search-result-import-path\">./components/Item.js</span>",
    "class"
  ],
  [
    "./components/itemscontainer.js~itemscontainer",
    "class/components/ItemsContainer.js~ItemsContainer.html",
    "<span>ItemsContainer</span> <span class=\"search-result-import-path\">./components/ItemsContainer.js</span>",
    "class"
  ],
  [
    "./components/modalgeneric.js~modalgeneric",
    "class/components/ModalGeneric.js~ModalGeneric.html",
    "<span>ModalGeneric</span> <span class=\"search-result-import-path\">./components/ModalGeneric.js</span>",
    "class"
  ],
  [
    "./components/modalpagegeneric.js~modalpagegeneric",
    "class/components/ModalPageGeneric.js~ModalPageGeneric.html",
    "<span>ModalPageGeneric</span> <span class=\"search-result-import-path\">./components/ModalPageGeneric.js</span>",
    "class"
  ],
  [
    "./components/index.js~root",
    "class/components/index.js~Root.html",
    "<span>Root</span> <span class=\"search-result-import-path\">./components/index.js</span>",
    "class"
  ],
  [
    "./components/sidebar.js~sidebar",
    "class/components/Sidebar.js~Sidebar.html",
    "<span>Sidebar</span> <span class=\"search-result-import-path\">./components/Sidebar.js</span>",
    "class"
  ],
  [
    "./components/apicall.js~apicall",
    "function/index.html#static-function-apiCall",
    "<span>apiCall</span> <span class=\"search-result-import-path\">./components/apiCall.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "components/addcategoryform.js",
    "file/components/AddCategoryForm.js.html",
    "components/AddCategoryForm.js",
    "file"
  ],
  [
    "components/addcategoryform.js~addcategoryform#addcategory",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-addCategory",
    "components/AddCategoryForm.js~AddCategoryForm#addCategory",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#advancestage",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-advanceStage",
    "components/AddCategoryForm.js~AddCategoryForm#advanceStage",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#constructor",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-constructor-constructor",
    "components/AddCategoryForm.js~AddCategoryForm#constructor",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#goback",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-goBack",
    "components/AddCategoryForm.js~AddCategoryForm#goBack",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#render",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-render",
    "components/AddCategoryForm.js~AddCategoryForm#render",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#resetfields",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-resetFields",
    "components/AddCategoryForm.js~AddCategoryForm#resetFields",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#state",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-member-state",
    "components/AddCategoryForm.js~AddCategoryForm#state",
    "member"
  ],
  [
    "components/addcategoryform.js~addcategoryform#switchmodalvisibility",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-switchModalVisibility",
    "components/AddCategoryForm.js~AddCategoryForm#switchModalVisibility",
    "method"
  ],
  [
    "components/addcategoryform.js~addcategoryform#updatename",
    "class/components/AddCategoryForm.js~AddCategoryForm.html#instance-method-updateName",
    "components/AddCategoryForm.js~AddCategoryForm#updateName",
    "method"
  ],
  [
    "components/additemform.js",
    "file/components/AddItemForm.js.html",
    "components/AddItemForm.js",
    "file"
  ],
  [
    "components/additemform.js~additemform#additem",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-addItem",
    "components/AddItemForm.js~AddItemForm#addItem",
    "method"
  ],
  [
    "components/additemform.js~additemform#advancestage",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-advanceStage",
    "components/AddItemForm.js~AddItemForm#advanceStage",
    "method"
  ],
  [
    "components/additemform.js~additemform#componentdidmount",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-componentDidMount",
    "components/AddItemForm.js~AddItemForm#componentDidMount",
    "method"
  ],
  [
    "components/additemform.js~additemform#constructor",
    "class/components/AddItemForm.js~AddItemForm.html#instance-constructor-constructor",
    "components/AddItemForm.js~AddItemForm#constructor",
    "method"
  ],
  [
    "components/additemform.js~additemform#goback",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-goBack",
    "components/AddItemForm.js~AddItemForm#goBack",
    "method"
  ],
  [
    "components/additemform.js~additemform#handledrop",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-handleDrop",
    "components/AddItemForm.js~AddItemForm#handleDrop",
    "method"
  ],
  [
    "components/additemform.js~additemform#haschanged",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-hasChanged",
    "components/AddItemForm.js~AddItemForm#hasChanged",
    "method"
  ],
  [
    "components/additemform.js~additemform#isvalidated",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-isValidated",
    "components/AddItemForm.js~AddItemForm#isValidated",
    "method"
  ],
  [
    "components/additemform.js~additemform#render",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-render",
    "components/AddItemForm.js~AddItemForm#render",
    "method"
  ],
  [
    "components/additemform.js~additemform#resetfields",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-resetFields",
    "components/AddItemForm.js~AddItemForm#resetFields",
    "method"
  ],
  [
    "components/additemform.js~additemform#state",
    "class/components/AddItemForm.js~AddItemForm.html#instance-member-state",
    "components/AddItemForm.js~AddItemForm#state",
    "member"
  ],
  [
    "components/additemform.js~additemform#stopevent",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-stopEvent",
    "components/AddItemForm.js~AddItemForm#stopEvent",
    "method"
  ],
  [
    "components/additemform.js~additemform#switchmodalvisibility",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-switchModalVisibility",
    "components/AddItemForm.js~AddItemForm#switchModalVisibility",
    "method"
  ],
  [
    "components/additemform.js~additemform#updatedescription",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-updateDescription",
    "components/AddItemForm.js~AddItemForm#updateDescription",
    "method"
  ],
  [
    "components/additemform.js~additemform#updatename",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-updateName",
    "components/AddItemForm.js~AddItemForm#updateName",
    "method"
  ],
  [
    "components/additemform.js~additemform#updateprice",
    "class/components/AddItemForm.js~AddItemForm.html#instance-method-updatePrice",
    "components/AddItemForm.js~AddItemForm#updatePrice",
    "method"
  ],
  [
    "components/category.js",
    "file/components/Category.js.html",
    "components/Category.js",
    "file"
  ],
  [
    "components/category.js~category#deletereactelement",
    "class/components/Category.js~Category.html#instance-member-DeleteReactElement",
    "components/Category.js~Category#DeleteReactElement",
    "member"
  ],
  [
    "components/category.js~category#editreactelement",
    "class/components/Category.js~Category.html#instance-member-EditReactElement",
    "components/Category.js~Category#EditReactElement",
    "member"
  ],
  [
    "components/category.js~category#constructor",
    "class/components/Category.js~Category.html#instance-constructor-constructor",
    "components/Category.js~Category#constructor",
    "method"
  ],
  [
    "components/category.js~category#displaycategory",
    "class/components/Category.js~Category.html#instance-method-displayCategory",
    "components/Category.js~Category#displayCategory",
    "method"
  ],
  [
    "components/category.js~category#render",
    "class/components/Category.js~Category.html#instance-method-render",
    "components/Category.js~Category#render",
    "method"
  ],
  [
    "components/category.js~category#state",
    "class/components/Category.js~Category.html#instance-member-state",
    "components/Category.js~Category#state",
    "member"
  ],
  [
    "components/category.js~category#switchdeletemodalvisibility",
    "class/components/Category.js~Category.html#instance-method-switchDeleteModalVisibility",
    "components/Category.js~Category#switchDeleteModalVisibility",
    "method"
  ],
  [
    "components/category.js~category#switcheditmodalvisibility",
    "class/components/Category.js~Category.html#instance-method-switchEditModalVisibility",
    "components/Category.js~Category#switchEditModalVisibility",
    "method"
  ],
  [
    "components/component.js",
    "file/components/Component.js.html",
    "components/Component.js",
    "file"
  ],
  [
    "components/component.js~component#autobind",
    "class/components/Component.js~Component.html#instance-method-autoBind",
    "components/Component.js~Component#autoBind",
    "method"
  ],
  [
    "components/component.js~component#bindmethods",
    "class/components/Component.js~Component.html#instance-method-bindMethods",
    "components/Component.js~Component#bindMethods",
    "method"
  ],
  [
    "components/component.js~component#constructor",
    "class/components/Component.js~Component.html#instance-constructor-constructor",
    "components/Component.js~Component#constructor",
    "method"
  ],
  [
    "components/deletecategoryform.js",
    "file/components/DeleteCategoryForm.js.html",
    "components/DeleteCategoryForm.js",
    "file"
  ],
  [
    "components/deletecategoryform.js~deletecategoryform#constructor",
    "class/components/DeleteCategoryForm.js~DeleteCategoryForm.html#instance-constructor-constructor",
    "components/DeleteCategoryForm.js~DeleteCategoryForm#constructor",
    "method"
  ],
  [
    "components/deletecategoryform.js~deletecategoryform#deletecategory",
    "class/components/DeleteCategoryForm.js~DeleteCategoryForm.html#instance-method-deleteCategory",
    "components/DeleteCategoryForm.js~DeleteCategoryForm#deleteCategory",
    "method"
  ],
  [
    "components/deletecategoryform.js~deletecategoryform#render",
    "class/components/DeleteCategoryForm.js~DeleteCategoryForm.html#instance-method-render",
    "components/DeleteCategoryForm.js~DeleteCategoryForm#render",
    "method"
  ],
  [
    "components/deleteitemform.js",
    "file/components/DeleteItemForm.js.html",
    "components/DeleteItemForm.js",
    "file"
  ],
  [
    "components/deleteitemform.js~deleteitemform#constructor",
    "class/components/DeleteItemForm.js~DeleteItemForm.html#instance-constructor-constructor",
    "components/DeleteItemForm.js~DeleteItemForm#constructor",
    "method"
  ],
  [
    "components/deleteitemform.js~deleteitemform#deleteitem",
    "class/components/DeleteItemForm.js~DeleteItemForm.html#instance-method-deleteItem",
    "components/DeleteItemForm.js~DeleteItemForm#deleteItem",
    "method"
  ],
  [
    "components/deleteitemform.js~deleteitemform#render",
    "class/components/DeleteItemForm.js~DeleteItemForm.html#instance-method-render",
    "components/DeleteItemForm.js~DeleteItemForm#render",
    "method"
  ],
  [
    "components/editcategoryform.js",
    "file/components/EditCategoryForm.js.html",
    "components/EditCategoryForm.js",
    "file"
  ],
  [
    "components/editcategoryform.js~editcategoryform#advancestage",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-advanceStage",
    "components/EditCategoryForm.js~EditCategoryForm#advanceStage",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#constructor",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-constructor-constructor",
    "components/EditCategoryForm.js~EditCategoryForm#constructor",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#editcategory",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-editCategory",
    "components/EditCategoryForm.js~EditCategoryForm#editCategory",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#goback",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-goBack",
    "components/EditCategoryForm.js~EditCategoryForm#goBack",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#haschanged",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-hasChanged",
    "components/EditCategoryForm.js~EditCategoryForm#hasChanged",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#render",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-render",
    "components/EditCategoryForm.js~EditCategoryForm#render",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#resetfields",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-resetFields",
    "components/EditCategoryForm.js~EditCategoryForm#resetFields",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#state",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-member-state",
    "components/EditCategoryForm.js~EditCategoryForm#state",
    "member"
  ],
  [
    "components/editcategoryform.js~editcategoryform#switchmodalvisibility",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-switchModalVisibility",
    "components/EditCategoryForm.js~EditCategoryForm#switchModalVisibility",
    "method"
  ],
  [
    "components/editcategoryform.js~editcategoryform#updatename",
    "class/components/EditCategoryForm.js~EditCategoryForm.html#instance-method-updateName",
    "components/EditCategoryForm.js~EditCategoryForm#updateName",
    "method"
  ],
  [
    "components/edititemform.js",
    "file/components/EditItemForm.js.html",
    "components/EditItemForm.js",
    "file"
  ],
  [
    "components/edititemform.js~edititemform#advancestage",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-advanceStage",
    "components/EditItemForm.js~EditItemForm#advanceStage",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#constructor",
    "class/components/EditItemForm.js~EditItemForm.html#instance-constructor-constructor",
    "components/EditItemForm.js~EditItemForm#constructor",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#edititem",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-editItem",
    "components/EditItemForm.js~EditItemForm#editItem",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#goback",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-goBack",
    "components/EditItemForm.js~EditItemForm#goBack",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#handledrop",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-handleDrop",
    "components/EditItemForm.js~EditItemForm#handleDrop",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#haschanged",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-hasChanged",
    "components/EditItemForm.js~EditItemForm#hasChanged",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#isvalidated",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-isValidated",
    "components/EditItemForm.js~EditItemForm#isValidated",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#render",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-render",
    "components/EditItemForm.js~EditItemForm#render",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#state",
    "class/components/EditItemForm.js~EditItemForm.html#instance-member-state",
    "components/EditItemForm.js~EditItemForm#state",
    "member"
  ],
  [
    "components/edititemform.js~edititemform#stopevent",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-stopEvent",
    "components/EditItemForm.js~EditItemForm#stopEvent",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#switchmodalvisibility",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-switchModalVisibility",
    "components/EditItemForm.js~EditItemForm#switchModalVisibility",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#updatedescription",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-updateDescription",
    "components/EditItemForm.js~EditItemForm#updateDescription",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#updatename",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-updateName",
    "components/EditItemForm.js~EditItemForm#updateName",
    "method"
  ],
  [
    "components/edititemform.js~edititemform#updateprice",
    "class/components/EditItemForm.js~EditItemForm.html#instance-method-updatePrice",
    "components/EditItemForm.js~EditItemForm#updatePrice",
    "method"
  ],
  [
    "components/googleauth2.js",
    "file/components/GoogleAuth2.js.html",
    "components/GoogleAuth2.js",
    "file"
  ],
  [
    "components/googleauth2.js~googleauth2#status",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-member-STATUS",
    "components/GoogleAuth2.js~GoogleAuth2#STATUS",
    "member"
  ],
  [
    "components/googleauth2.js~googleauth2#componentdidmount",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-method-componentDidMount",
    "components/GoogleAuth2.js~GoogleAuth2#componentDidMount",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#constructor",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-constructor-constructor",
    "components/GoogleAuth2.js~GoogleAuth2#constructor",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#onsessionchange",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-method-onSessionChange",
    "components/GoogleAuth2.js~GoogleAuth2#onSessionChange",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#render",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-method-render",
    "components/GoogleAuth2.js~GoogleAuth2#render",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#signinfailure",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-method-signInFailure",
    "components/GoogleAuth2.js~GoogleAuth2#signInFailure",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#signinsuccess",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-method-signInSuccess",
    "components/GoogleAuth2.js~GoogleAuth2#signInSuccess",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#signout",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-method-signOut",
    "components/GoogleAuth2.js~GoogleAuth2#signOut",
    "method"
  ],
  [
    "components/googleauth2.js~googleauth2#state",
    "class/components/GoogleAuth2.js~GoogleAuth2.html#instance-member-state",
    "components/GoogleAuth2.js~GoogleAuth2#state",
    "member"
  ],
  [
    "components/item.js",
    "file/components/Item.js.html",
    "components/Item.js",
    "file"
  ],
  [
    "components/item.js~item#deletereactelement",
    "class/components/Item.js~Item.html#instance-member-DeleteReactElement",
    "components/Item.js~Item#DeleteReactElement",
    "member"
  ],
  [
    "components/item.js~item#editreactelement",
    "class/components/Item.js~Item.html#instance-member-EditReactElement",
    "components/Item.js~Item#EditReactElement",
    "member"
  ],
  [
    "components/item.js~item#status",
    "class/components/Item.js~Item.html#instance-member-STATUS",
    "components/Item.js~Item#STATUS",
    "member"
  ],
  [
    "components/item.js~item#constructor",
    "class/components/Item.js~Item.html#instance-constructor-constructor",
    "components/Item.js~Item#constructor",
    "method"
  ],
  [
    "components/item.js~item#render",
    "class/components/Item.js~Item.html#instance-method-render",
    "components/Item.js~Item#render",
    "method"
  ],
  [
    "components/item.js~item#state",
    "class/components/Item.js~Item.html#instance-member-state",
    "components/Item.js~Item#state",
    "member"
  ],
  [
    "components/item.js~item#switchdeletemodalvisibility",
    "class/components/Item.js~Item.html#instance-method-switchDeleteModalVisibility",
    "components/Item.js~Item#switchDeleteModalVisibility",
    "method"
  ],
  [
    "components/item.js~item#switcheditmodalvisibility",
    "class/components/Item.js~Item.html#instance-method-switchEditModalVisibility",
    "components/Item.js~Item#switchEditModalVisibility",
    "method"
  ],
  [
    "components/itemscontainer.js",
    "file/components/ItemsContainer.js.html",
    "components/ItemsContainer.js",
    "file"
  ],
  [
    "components/itemscontainer.js~itemscontainer#constructor",
    "class/components/ItemsContainer.js~ItemsContainer.html#instance-constructor-constructor",
    "components/ItemsContainer.js~ItemsContainer#constructor",
    "method"
  ],
  [
    "components/itemscontainer.js~itemscontainer#reactcomponent",
    "class/components/ItemsContainer.js~ItemsContainer.html#instance-member-reactComponent",
    "components/ItemsContainer.js~ItemsContainer#reactComponent",
    "member"
  ],
  [
    "components/itemscontainer.js~itemscontainer#reactelement",
    "class/components/ItemsContainer.js~ItemsContainer.html#instance-member-reactElement",
    "components/ItemsContainer.js~ItemsContainer#reactElement",
    "member"
  ],
  [
    "components/itemscontainer.js~itemscontainer#render",
    "class/components/ItemsContainer.js~ItemsContainer.html#instance-method-render",
    "components/ItemsContainer.js~ItemsContainer#render",
    "method"
  ],
  [
    "components/itemscontainer.js~itemscontainer#state",
    "class/components/ItemsContainer.js~ItemsContainer.html#instance-member-state",
    "components/ItemsContainer.js~ItemsContainer#state",
    "member"
  ],
  [
    "components/itemscontainer.js~itemscontainer#switchmodalvisibility",
    "class/components/ItemsContainer.js~ItemsContainer.html#instance-method-switchModalVisibility",
    "components/ItemsContainer.js~ItemsContainer#switchModalVisibility",
    "method"
  ],
  [
    "components/modalgeneric.js",
    "file/components/ModalGeneric.js.html",
    "components/ModalGeneric.js",
    "file"
  ],
  [
    "components/modalgeneric.js~modalgeneric#componentdidmount",
    "class/components/ModalGeneric.js~ModalGeneric.html#instance-method-componentDidMount",
    "components/ModalGeneric.js~ModalGeneric#componentDidMount",
    "method"
  ],
  [
    "components/modalgeneric.js~modalgeneric#constructor",
    "class/components/ModalGeneric.js~ModalGeneric.html#instance-constructor-constructor",
    "components/ModalGeneric.js~ModalGeneric#constructor",
    "method"
  ],
  [
    "components/modalgeneric.js~modalgeneric#handleclick",
    "class/components/ModalGeneric.js~ModalGeneric.html#instance-method-handleClick",
    "components/ModalGeneric.js~ModalGeneric#handleClick",
    "method"
  ],
  [
    "components/modalgeneric.js~modalgeneric#render",
    "class/components/ModalGeneric.js~ModalGeneric.html#instance-method-render",
    "components/ModalGeneric.js~ModalGeneric#render",
    "method"
  ],
  [
    "components/modalgeneric.js~modalgeneric#state",
    "class/components/ModalGeneric.js~ModalGeneric.html#instance-member-state",
    "components/ModalGeneric.js~ModalGeneric#state",
    "member"
  ],
  [
    "components/modalpagegeneric.js",
    "file/components/ModalPageGeneric.js.html",
    "components/ModalPageGeneric.js",
    "file"
  ],
  [
    "components/modalpagegeneric.js~modalpagegeneric#constructor",
    "class/components/ModalPageGeneric.js~ModalPageGeneric.html#instance-constructor-constructor",
    "components/ModalPageGeneric.js~ModalPageGeneric#constructor",
    "method"
  ],
  [
    "components/modalpagegeneric.js~modalpagegeneric#render",
    "class/components/ModalPageGeneric.js~ModalPageGeneric.html#instance-method-render",
    "components/ModalPageGeneric.js~ModalPageGeneric#render",
    "method"
  ],
  [
    "components/modalpagegeneric.js~modalpagegeneric#stopevent",
    "class/components/ModalPageGeneric.js~ModalPageGeneric.html#instance-method-stopEvent",
    "components/ModalPageGeneric.js~ModalPageGeneric#stopEvent",
    "method"
  ],
  [
    "components/sidebar.js",
    "file/components/Sidebar.js.html",
    "components/Sidebar.js",
    "file"
  ],
  [
    "components/sidebar.js~sidebar#constructor",
    "class/components/Sidebar.js~Sidebar.html#instance-constructor-constructor",
    "components/Sidebar.js~Sidebar#constructor",
    "method"
  ],
  [
    "components/sidebar.js~sidebar#reactelement",
    "class/components/Sidebar.js~Sidebar.html#instance-member-reactElement",
    "components/Sidebar.js~Sidebar#reactElement",
    "member"
  ],
  [
    "components/sidebar.js~sidebar#render",
    "class/components/Sidebar.js~Sidebar.html#instance-method-render",
    "components/Sidebar.js~Sidebar#render",
    "method"
  ],
  [
    "components/sidebar.js~sidebar#setactivecategory",
    "class/components/Sidebar.js~Sidebar.html#instance-method-setActiveCategory",
    "components/Sidebar.js~Sidebar#setActiveCategory",
    "method"
  ],
  [
    "components/sidebar.js~sidebar#state",
    "class/components/Sidebar.js~Sidebar.html#instance-member-state",
    "components/Sidebar.js~Sidebar#state",
    "member"
  ],
  [
    "components/sidebar.js~sidebar#switchmodalvisibility",
    "class/components/Sidebar.js~Sidebar.html#instance-method-switchModalVisibility",
    "components/Sidebar.js~Sidebar#switchModalVisibility",
    "method"
  ],
  [
    "components/apicall.js",
    "file/components/apiCall.js.html",
    "components/apiCall.js",
    "file"
  ],
  [
    "components/index.js",
    "file/components/index.js.html",
    "components/index.js",
    "file"
  ],
  [
    "components/index.js~root#status",
    "class/components/index.js~Root.html#instance-member-STATUS",
    "components/index.js~Root#STATUS",
    "member"
  ],
  [
    "components/index.js~root#addcategory",
    "class/components/index.js~Root.html#instance-method-addCategory",
    "components/index.js~Root#addCategory",
    "method"
  ],
  [
    "components/index.js~root#additem",
    "class/components/index.js~Root.html#instance-method-addItem",
    "components/index.js~Root#addItem",
    "method"
  ],
  [
    "components/index.js~root#componentdidmount",
    "class/components/index.js~Root.html#instance-method-componentDidMount",
    "components/index.js~Root#componentDidMount",
    "method"
  ],
  [
    "components/index.js~root#constructor",
    "class/components/index.js~Root.html#instance-constructor-constructor",
    "components/index.js~Root#constructor",
    "method"
  ],
  [
    "components/index.js~root#deletecategory",
    "class/components/index.js~Root.html#instance-method-deleteCategory",
    "components/index.js~Root#deleteCategory",
    "method"
  ],
  [
    "components/index.js~root#deleteitem",
    "class/components/index.js~Root.html#instance-method-deleteItem",
    "components/index.js~Root#deleteItem",
    "method"
  ],
  [
    "components/index.js~root#displaycategory",
    "class/components/index.js~Root.html#instance-method-displayCategory",
    "components/index.js~Root#displayCategory",
    "method"
  ],
  [
    "components/index.js~root#editcategory",
    "class/components/index.js~Root.html#instance-method-editCategory",
    "components/index.js~Root#editCategory",
    "method"
  ],
  [
    "components/index.js~root#edititem",
    "class/components/index.js~Root.html#instance-method-editItem",
    "components/index.js~Root#editItem",
    "method"
  ],
  [
    "components/index.js~root#loadcategories",
    "class/components/index.js~Root.html#instance-method-loadCategories",
    "components/index.js~Root#loadCategories",
    "method"
  ],
  [
    "components/index.js~root#onsessionchange",
    "class/components/index.js~Root.html#instance-method-onSessionChange",
    "components/index.js~Root#onSessionChange",
    "method"
  ],
  [
    "components/index.js~root#render",
    "class/components/index.js~Root.html#instance-method-render",
    "components/index.js~Root#render",
    "method"
  ],
  [
    "components/index.js~root#state",
    "class/components/index.js~Root.html#instance-member-state",
    "components/index.js~Root#state",
    "member"
  ],
  [
    "components/index.js~root#updatenonce",
    "class/components/index.js~Root.html#instance-method-updateNonce",
    "components/index.js~Root#updateNonce",
    "method"
  ]
]